-- Criar schema (em Oracle, usamos usuário em vez de schema)
-- No Oracle Live SQL, normalmente você já está dentro do seu usuário, então não precisa de CREATE SCHEMA.
-- Basta rodar os CREATE TABLE.

-- ===============================
-- Tabela: convenio
-- ===============================
CREATE TABLE convenio (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100),
  tipoplano VARCHAR2(100),
  datavalidade DATE,
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1
);

-- ===============================
-- Tabela: usuario
-- ===============================
CREATE TABLE usuario (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100),
  endereco VARCHAR2(200),
  telefone VARCHAR2(15),
  email VARCHAR2(100),
  convenioid NUMBER,
  senha VARCHAR2(100),
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1,
  CONSTRAINT fk_usuario_convenio FOREIGN KEY (convenioid) REFERENCES convenio (id)
);

-- ===============================
-- Tabela: animal
-- ===============================
CREATE TABLE animal (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100),
  especie VARCHAR2(50),
  raca VARCHAR2(50),
  datanascimento DATE,
  tutorid NUMBER,
  convenioid NUMBER,
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1,
  CONSTRAINT fk_animal_tutor FOREIGN KEY (tutorid) REFERENCES usuario (id),
  CONSTRAINT fk_animal_convenio FOREIGN KEY (convenioid) REFERENCES convenio (id)
);

-- ===============================
-- Tabela: clinica
-- ===============================
CREATE TABLE clinica (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100),
  endereco VARCHAR2(200),
  telefone VARCHAR2(15),
  email VARCHAR2(100),
  senha VARCHAR2(100),
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1
);

-- ===============================
-- Tabela: veterinario
-- ===============================
CREATE TABLE veterinario (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR2(100),
  telefone VARCHAR2(15),
  email VARCHAR2(100),
  registroprofissional VARCHAR2(50),
  clinicaid NUMBER,
  senha VARCHAR2(100),
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1,
  CONSTRAINT fk_vet_clinica FOREIGN KEY (clinicaid) REFERENCES clinica (id)
);

-- ===============================
-- Tabela: historicomedico
-- ===============================
CREATE TABLE historicomedico (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataconsulta DATE,
  diagnostico VARCHAR2(200),
  tratamento VARCHAR2(200),
  observacoes VARCHAR2(200),
  exameclinico CLOB, -- substituindo JSON por CLOB (texto longo)
  animalid NUMBER,
  veterinarioid NUMBER,
  datacriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataatualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dataexclusao TIMESTAMP,
  ativo NUMBER(1) DEFAULT 1,
  CONSTRAINT fk_hist_animal FOREIGN KEY (animalid) REFERENCES animal (id),
  CONSTRAINT fk_hist_vet FOREIGN KEY (veterinarioid) REFERENCES veterinario (id)
);

-- ===============================
-- Trigger: Atualizar data de atualização em ANIMAL
-- ===============================
CREATE OR REPLACE TRIGGER trg_animal_update
BEFORE UPDATE ON animal
FOR EACH ROW
BEGIN
  :NEW.dataatualizacao := CURRENT_TIMESTAMP;
END;
/

